/** Global **/
export const SET_CURRENCY = 'SET_CURRENCY';

/** Front coins **/
export const FETCH_COINS_REQUEST = 'FETCH_COINS_REQUEST';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAILURE = 'FETCH_COINS_FAILURE';
export const RECEIVE_COINS = 'RECEIVE_COINS';

/** Global coins **/
export const FETCH_GLOBAL_REQUEST = 'FETCH_GLOBAL_REQUEST';
export const FETCH_GLOBAL_SUCCESS = 'FETCH_GLOBAL_SUCCESS';
export const FETCH_GLOBAL_FAILURE = 'FETCH_GLOBAL_FAILURE';
export const RECEIVE_GLOBAL = 'RECEIVE_GLOBAL';

/** Socket coicap change **/
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_TRADES = 'SOCKET_TRADES';
//export const NEW_TRADES_RECEIVED = 'NEW_TRADES_RECEIVED';
export const NEW_COIN_VALUE = 'NEW_COIN_VALUE';


/** Fixer IO **/

export const FETCH_LATEST_CHANGE_REQUEST = 'FETCH_LATEST_CHANGE_REQUEST';
export const FETCH_LATEST_CHANGE_SUCCESS = 'FETCH_LATEST_CHANGE_SUCCESS';
export const FETCH_LATEST_CHANGE_FAILURE = 'FETCH_LATEST_CHANGE_FAILURE';
export const RECEIVE_LATEST_CHANGE = 'RECEIVE_LATEST_CHANGE';